//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guest_Entry_Recording_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public long id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string licence_number { get; set; }
        public string sub_city { get; set; }
        public string car_type { get; set; }
        public string plate_number { get; set; }
        public string dest_office { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
