//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guest_Entry_Recording_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class gun
    {
        public long id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string cupon_number { get; set; }
        public string gun_type { get; set; }
        public string side_number { get; set; }
        public Nullable<bool> isTaken { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
