//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guest_Entry_Recording_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class federal1Entities4 : DbContext
    {
        public federal1Entities4()
            : base("name=federal1Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car_recipents> car_recipents { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<failed_jobs> failed_jobs { get; set; }
        public virtual DbSet<guest_recipents> guest_recipents { get; set; }
        public virtual DbSet<guest> guests { get; set; }
        public virtual DbSet<gun_recipents> gun_recipents { get; set; }
        public virtual DbSet<gun> guns { get; set; }
        public virtual DbSet<intern> interns { get; set; }
        public virtual DbSet<migration> migrations { get; set; }
        public virtual DbSet<personal_access_tokens> personal_access_tokens { get; set; }
        public virtual DbSet<recipent> recipents { get; set; }
        public virtual DbSet<rrequest> rrequests { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<weekend> weekends { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
    }
}
